version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8081:80
    container_name: 'frontend'
    depends_on:
      - gateway
    networks:
      - voting-system

  gateway:
    build:
      context: ./gateway/src
      dockerfile: Dockerfile
    container_name: 'gateway'
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - voting-system

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: 'user-service'
    ports:
      - 50051:50051
    env_file:
      - .env
    networks:
      - voting-system

  poll-service:
    build:
      context: ./poll-service
      dockerfile: Dockerfile
    container_name: 'poll-service'
    ports:
      - 50052:50052
    env_file:
      - .env
    networks:
      - voting-system

  result-service:
    build:
      context: ./result-service
      dockerfile: Dockerfile
    container_name: 'result-service'
    ports:
      - 50053:50053
    env_file:
      - .env
    networks:
      - voting-system

  vote-producer:
    build:
      context: ./vote-service/producer
      dockerfile: Dockerfile
    container_name: 'vote-producer'
    ports:
      - 50054:50054
    depends_on:
      - kafka
    env_file:
      - .env
    networks:
      - voting-system

  vote-consumer:
    build:
      context: ./vote-service/consumer
      dockerfile: Dockerfile
    container_name: 'vote-consumer'
    depends_on:
      - kafka
      - vote-producer
    env_file:
      - .env
    networks:
      - voting-system

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    container_name: 'zookeeper'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - voting-system

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CREATE_TOPICS=votes:5:2
    depends_on:
      - zookeeper
    networks:
      - voting-system

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: 'nginx'
    ports:
      - 80:8081
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    depends_on:
      - frontend
      - gateway
    networks:
      - voting-system

networks:
  voting-system:
    driver: bridge