apiVersion: v1
data:
  nginx.conf: |-
    server {
        listen 8081;

        location /api/ {
            rewrite ^/api(/.*)$ $1 break;
            proxy_pass http://gateway:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            proxy_pass http://frontend:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

    }
kind: ConfigMap
metadata:
  creationTimestamp: "2023-06-18T10:24:58Z"
  name: nginx-config
  namespace: default
  resourceVersion: "284996"
  uid: bbc38325-6729-4b20-bca1-461f93b3b98b
