apiVersion: v1
data:
  nginx.conf: |
    server {
    listen 8081;

    location /api/ {
        rewrite ^/api(/.*)$ $1 break;
        proxy_pass http://gateway:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }

    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"nginx.conf":"server {\nlisten 8081;\n\nlocation /api/ {\n    rewrite ^/api(/.*)$ $1 break;\n    proxy_pass http://gateway:8080;\n    proxy_set_header Host $host;\n    proxy_set_header X-Real-IP $remote_addr;\n  }\n\nlocation / {\n    proxy_pass http://frontend:80;\n    proxy_set_header Host $host;\n    proxy_set_header X-Real-IP $remote_addr;\n  }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"nginx-configmap","namespace":"default"}}
  creationTimestamp: "2023-06-18T10:51:36Z"
  name: nginx-configmap
  namespace: default
  resourceVersion: "322763"
  uid: ea910190-7918-4a32-92ee-8a0935ed1990
