apiVersion: v1
data:
  DATABASE_URL: mysql://nezu80du7c7kd9j1y8q6:pscale_pw_Ba5mE3SjXYIK80b4FUcknF0LAGPBEeQ7OiglYJADYhX@aws.connect.psdb.cloud/voting-system?sslaccept=strict
kind: ConfigMap
metadata:
  creationTimestamp: "2023-06-18T04:24:08Z"
  labels:
    app: poll-service
  name: poll-service-config-hkvp
  namespace: default
  resourceVersion: "14015"
  uid: 4a2920c6-e0be-4308-a6bd-de756d2d651d
