apiVersion: v1
data:
  DATABASE_URL: mysql://nezu80du7c7kd9j1y8q6:pscale_pw_Ba5mE3SjXYIK80b4FUcknF0LAGPBEeQ7OiglYJADYhX@aws.connect.psdb.cloud/voting-system?sslaccept=strict
kind: ConfigMap
metadata:
  creationTimestamp: "2023-06-18T04:24:38Z"
  labels:
    app: result-service
  name: result-service-config-lhkv
  namespace: default
  resourceVersion: "14552"
  uid: 3ce73a6c-45ed-4682-afb3-7859eb8030fb
