apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autopilot.gke.io/resource-adjustment: '{"input":{"containers":[{"name":"zookeeper-sha256-1"}]},"output":{"containers":[{"limits":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"2Gi"},"requests":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"2Gi"},"name":"zookeeper-sha256-1"}]},"modified":true}'
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-06-18T04:21:24Z"
  generation: 2
  labels:
    app: zookeeper
  name: zookeeper
  namespace: default
  resourceVersion: "28572"
  uid: dce9c60a-ee57-42a2-959e-573dfdc46893
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: zookeeper
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zookeeper
    spec:
      containers:
      - env:
        - name: ALLOW_ANONYMOUS_LOGIN
          valueFrom:
            configMapKeyRef:
              key: ALLOW_ANONYMOUS_LOGIN
              name: zookeeper-config-xffn
        image: asia-southeast1-docker.pkg.dev/csc3004-group24-voting-system/voting-system-repo/zookeeper@sha256:c01a016ce0d5ee84c167d8ddbeb39e7bcad647872a679015ad313676b1e63022
        imagePullPolicy: IfNotPresent
        name: zookeeper-sha256-1
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/arch
        operator: Equal
        value: amd64
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-06-18T04:21:24Z"
    lastUpdateTime: "2023-06-18T04:23:42Z"
    message: ReplicaSet "zookeeper-7f965ddbc4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-06-18T04:38:19Z"
    lastUpdateTime: "2023-06-18T04:38:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
