apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2023-06-18T10:47:10Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: frontend
  name: frontend
  namespace: default
  resourceVersion: "301698"
  uid: 0abb3334-6a3c-4edd-8e2e-258c9ba97ef9
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.46.3.90
  clusterIPs:
  - 10.46.3.90
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30135
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.124.178.54
