apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2023-06-18T10:33:45Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: nginx
  name: nginx
  namespace: default
  resourceVersion: "291990"
  uid: 6f1504f2-eb7a-41a4-a473-e88cd75a4fd3
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.46.3.19
  clusterIPs:
  - 10.46.3.19
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30207
    port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.124.186.134
