apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2023-06-18T08:53:39Z"
  labels:
    app: user-service
  name: user-service
  namespace: default
  resourceVersion: "217474"
  uid: 3af10b6c-157e-40fb-9a75-051631e0312a
spec:
  clusterIP: 10.46.1.71
  clusterIPs:
  - 10.46.1.71
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: user-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
