apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2023-06-18T08:52:56Z"
  labels:
    app: zookeeper
  name: zookeeper
  namespace: default
  resourceVersion: "216827"
  uid: d7759a1b-ed12-44ba-9ca2-d8c14927d118
spec:
  clusterIP: 10.46.3.195
  clusterIPs:
  - 10.46.3.195
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    app: zookeeper
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
